### ISSUE TITLE
Wrong release order

### ISSUE THREAD

**Issue by 1n** [voxpupuli/puppet-blacksmith#38]
Rakefile

``` ruby
require 'puppet_blacksmith/rake_tasks'

Blacksmith::RakeTask.new do |t|
  t.tag_pattern = "%s"
  t.build = false # do not build the module nor push it to the Forge, just do the tagging [:clean, :tag, :bump_commit]
end
```

```
$ git tag
0.1.0
$ bundle exec rake module:version
0.1.0
$ bundle exec rake module:version:next
0.1.1
```

Simulating bundle exec rake module:release steps
https://github.com/voxpupuli/puppet-blacksmith/blob/v3.4.0/lib/puppet_blacksmith/rake_tasks.rb#L127

``` ruby
desc "Release the Puppet module, doing a clean, build, tag, push, bump_commit and git push."
release_dependencies = @build ? [:clean, :build, :tag, :push, :bump_commit] : [:clean, :tag, :bump_commit]
task :release => release_dependencies do
  puts "Pushing to remote git repo"
  Blacksmith::Git.new.push!
end
```

```
$ bundle exec rake module:tag
rake aborted!
Blacksmith::Error: Command git --git-dir=/home/vtk/wk/modules/some_module/.git --work-tree=/home/vtk/wk/modules/some_module tag 0.1.0 failed with exit status pid 27426 exit 128
fatal: tag '0.1.0' already exists
/home/vtk/.rvm/gems/ruby-2.0.0-p643/gems/puppet-blacksmith-3.4.0/lib/puppet_blacksmith/git.rb:56:in `exec_git'
/home/vtk/.rvm/gems/ruby-2.0.0-p643/gems/puppet-blacksmith-3.4.0/lib/puppet_blacksmith/git.rb:20:in `tag!'
/home/vtk/.rvm/gems/ruby-2.0.0-p643/gems/puppet-blacksmith-3.4.0/lib/puppet_blacksmith/rake_tasks.rb:72:in `block (2 levels) in define'
/home/vtk/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/home/vtk/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => module:tag
(See full trace by running task with --trace)
$ bundle exec rake module:version
0.1.0
```

If in a different order first :bump_commit then :tag and git push - everything is fine and you get commited version with correct tag, else tag points to a metadata.json with old version.

```
$ git tag
0.1.0
$ bundle exec rake module:version                                                                                                                                                             
0.1.0
$ bundle exec rake module:version:next
0.1.1
$ bundle exec rake module:bump_commit
Bumping version from 0.1.0 to 0.1.1
$ bundle exec rake module:version
0.1.1
$ bundle exec rake module:tag
$ git tag
0.1.0
0.1.1
$ git log --no-walk --tags --pretty="%h %d %s" --decorate=full
5043fcb  (HEAD -> refs/heads/master, tag: refs/tags/0.1.1) [blacksmith] Bump version to 0.1.1
```

**Comment by ekohl** [comment]
With #42 merged I think this can be closed.
