### ISSUE TITLE
artifactory uploads

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-blacksmith#72]
@bodgit (couldn't find you on slack)

I'm trying to test so wanted ask for your help:

Updated Gemfile to allow for ENV override:
```
  gem "puppet-blacksmith", *location_for(ENV['BLACKSMITH_VERSION'] || '~> 4.0.1')
```
```
puppet/profile_base - [dev●] » BLACKSMITH_FORGE_URL=https://artifactory.example.com/api/puppet/puppet BLACKSMITH_FORGE_TYPE=artifactory BLACKSMITH_FORGE_TOKEN=REDACTED BLACKSMITH_VERSION="git://github.com/voxpupuli/puppet-blacksmith.git#master" bundle exec rake module:push
pdk (INFO): Building ap-profile_base version 2.2.0
pdk (INFO): Build of ap-profile_base has completed successfully. Built package can be found here: /Users/cdenneen/src/gitlab/puppet/profile_base/pkg/ap-profile_base-2.2.0.tar.gz
Uploading to Puppet Forge ap/profile_base
rake aborted!
NameError: undefined local variable or method `package' for #<Blacksmith::Forge:0x00007ffba833fb70>
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:61:in `rescue in upload'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:53:in `upload'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:48:in `push!'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/rake_tasks.rb:133:in `block (2 levels) in define'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'

Caused by:
RestClient::Exceptions::ReadTimeout: Timed out reading data from server
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:733:in `rescue in transmit'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:642:in `transmit'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:56:in `upload'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:48:in `push!'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/rake_tasks.rb:133:in `block (2 levels) in define'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'

Caused by:
Net::ReadTimeout: Net::ReadTimeout
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:446:in `net_http_do_request'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:721:in `block in transmit'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:56:in `upload'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/forge.rb:48:in `push!'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/bundler/gems/puppet-blacksmith-068489b2bec7/lib/puppet_blacksmith/rake_tasks.rb:133:in `block (2 levels) in define'
/Users/cdenneen/src/gitlab/puppet/profile_base/.bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/cdenneen/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'
Tasks: TOP => module:push
(See full trace by running task with --trace)
```

Maybe I'm missing something

**Comment by rtib** [comment]
The main problem here is
`NameError: undefined local variable or method `package' for #<Blacksmith::Forge:0x00007ffba833fb70>`

which is caused at [forge.rb#L61](https://github.com/voxpupuli/puppet-blacksmith/blob/775f582e500468d8896dfc9e22e96379a12d240e/lib/puppet_blacksmith/forge.rb#L61), because there is no local variable named `package`, it's `file` and there is no local variable `url`.

Both seem fixed with #76 which is merged but not released yet.
